/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import edu.princeton.cs.algs4.Draw;

public class App {
    edu.princeton.cs.algs4.Draw draw;

    public App(){
        this.draw = new Draw();
        this.draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.draw.setCanvasSize(1000, 600);
        this.draw.setXscale(0,1000);
        this.draw.setYscale(0,600);


        Grade grade = new Grade(10,5);
        Grade grade2 = new Grade(550,5);
        Navio navio = new Navio();
        navio.desenhar(0, 0, 4, "Horizontal", grade, draw);
        navio.desenhar(8, 1, 2, "Horizontal", grade, draw);
        navio.desenhar(2, 3, 5, "Vertical", grade, draw);
        navio.desenhar(1, 5, 3, "Vertical", grade, draw);
        navio.desenhar(5, 7, 3, "Vertical", grade, draw);
        grade.desenhar(draw);
        grade2.desenhar(draw);

    }

    public static void main(String[] args) {
        App app = new App();

        app.draw.show();
    }
}

